# Generated by Django 5.1.7 on 2025-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default='نامشخص', max_length=50),
        ),
        migrations.AddField(
            model_name='usernotregister',
            name='location',
            field=models.CharField(default='نامشخص', max_length=50),
        ),
    ]
