# Generated by Django 5.1.7 on 2025-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location_usernotregister_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('passenger', 'مسافر'), ('driver', 'راننده'), ('vendor', 'فروشنده'), ('admin', 'مدیر روستا/دهیار'), ('council', 'شورا')], max_length=50),
        ),
    ]
