# Generated by Django 5.1.7 on 2025-10-31 21:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('normal', 'Normal'), ('hurryup', 'Hurry Up'), ('vip', 'VIP')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.CharField(choices=[('city', 'شهر'), ('village', 'روستا')], max_length=20)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'راننده'}, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_driver_trips', to='users.user')),
                ('passenger', models.ForeignKey(limit_choices_to={'role': 'مسافر'}, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_passenger_trips', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentTripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('normal', 'Normal'), ('hurryup', 'Hurry Up'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('request_time', models.TimeField(default=django.utils.timezone.now)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_tripes', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='DriverQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('city', 'شهر'), ('village', 'روستا')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'راننده'}, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TableTripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('normal', 'Normal'), ('hurryup', 'Hurry Up'), ('vip', 'VIP')], max_length=20)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('passenger', models.ForeignKey(limit_choices_to={'role': 'مسافر'}, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
