# Generated by Django 5.1.7 on 2025-08-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('instant', 'درخواست فوری'), ('scheduled', 'درخواست زمان\u200cبندی شده')], max_length=20)),
                ('service_type', models.CharField(choices=[('go', 'رفت'), ('return', 'برگشت')], max_length=10)),
                ('is_hurry', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید راننده'), ('accepted', 'پذیرفته شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده')], default='pending', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_trips', to='users.user')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_requests', to='users.user')),
            ],
        ),
    ]
