# Generated by Django 5.1.7 on 2025-10-31 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentTripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('normal', 'Normal'), ('hurryup', 'Hurry Up'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('request_time', models.TimeField(default=django.utils.timezone.now)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_tripes', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='TableTripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('normal', 'Normal'), ('hurryup', 'Hurry Up'), ('vip', 'VIP')], max_length=10)),
                ('request_time', models.TimeField()),
                ('request_date', models.DateField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_tripes', to='users.user')),
            ],
        ),
    ]
