# Generated by Django 5.1.7 on 2025-10-31 21:19

import django.db.models.deletion
import django.utils.timezone
import ride.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletripe',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tabletripe',
            name='time',
        ),
        migrations.AddField(
            model_name='tabletripe',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tabletripe',
            name='request_time',
            field=models.TimeField(default=ride.models.current_time),
        ),
        migrations.AlterField(
            model_name='tabletripe',
            name='passenger',
            field=models.ForeignKey(limit_choices_to={'role': 'مسافر'}, on_delete=django.db.models.deletion.CASCADE, related_name='table_tripes', to='users.user'),
        ),
    ]
