# Generated by Django 5.1.7 on 2025-11-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_remove_tabletripe_date_remove_tabletripe_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenttripe',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
