# Generated by Django 5.1.7 on 2025-08-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_riderequest'),
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='price',
        ),
        migrations.AddField(
            model_name='riderequest',
            name='is_hurry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='origin',
            field=models.CharField(default='نامشخص', max_length=100),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='request_type',
            field=models.CharField(choices=[('scheduled', 'شب قبل'), ('normal', 'عادی')], default='نامشخص', max_length=20),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DriverQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='users.user')),
            ],
            options={
                'unique_together': {('driver', 'location')},
            },
        ),
        migrations.DeleteModel(
            name='TripRequest',
        ),
    ]
