# Generated by Django 5.1.7 on 2025-10-21 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_driverqueue'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_trips', to='users.user'),
        ),
    ]
