# Generated by Django 5.1.7 on 2025-11-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_currenttripe_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedtrip',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
