# Generated by Django 5.1.7 on 2025-10-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_triprequest_accepted_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverqueue',
            name='direction',
            field=models.CharField(choices=[('روستا به شهر', 'روستا به شهر'), ('شهر به روستا', 'شهر به روستا')], max_length=20),
        ),
        migrations.AlterField(
            model_name='driverqueue',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'راننده'}, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
