# Generated by Django 5.1.7 on 2025-11-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_acceptedtrip_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedtrip',
            name='current_trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_info', to='ride.currenttripe'),
        ),
    ]
