# Generated by Django 5.1.7 on 2025-11-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0005_acceptedtrip_current_trip'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedTripTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_driver', to='users.user')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_passenger', to='users.user')),
            ],
        ),
    ]
